INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE) VALUES
    ( 1, 'USD', 'BRL', 5.20);
INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE) VALUES
    ( 2, 'USD', 'CAN', 1.5);
INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE) VALUES
    ( 3, 'USD', 'ARG', 150.0);